# Jekyll configuration

#
# Site settings
#
name: Jian Lu
title: Jian Lu's Personal Site
description: I am a data scientist and software developer, and ...
logo_image: "/images/logo.png"
headshot_image: "/images/headshot.jpg"

# Url is currently only used only for the RSS feed in feed.xml
url: ""
baseurl: ""
social:
  email: zzzdevil@gmail.com
  github: jianlu
  QQ:
  weibo:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  linkedin: jianlu0219
  facebook:
  flickr:
  twitter:
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
  instagram:
  lastfm:
  rss: feed.xml

#
# Build settings
#
# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
gems: [jekyll-paginate]
paginate: 8
paginate_path: page/:num

permalink: /:year/:month/:title/
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  syntax_highlighter: rouge

exclude: ['README.md', 'LICENSE']


#
# Other settings
#
# Google Analytics key, leave blank to ignore
google_analytics_key: UA-73497007-1

# Comment system
comment:
  disqus: true
  disqus_url: "http://jianlu.github.io"
  disqus_identifier: 'JianIsAwesome'

# Share
share:
  baidu: true
